version: '3.8'

services:
  django:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    #env_file:
    #  - .env
    depends_on:
      - db
      - redis
  celery:
    build: .
    command: celery -A config worker -l INFO
    volumes:
      - .:/code
    depends_on:
      - django
      - redis
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
  redis:
    image: "redis:alpine"
volumes:
  pgdata: