# Generated by Django 3.2.9 on 2021-11-09 18:18

from django.db import migrations, models
import swings.models


class Migration(migrations.Migration):

    dependencies = [
        ('swings', '0003_alter_swing_recording'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swing',
            name='recording',
            field=models.FileField(blank=True, upload_to=swings.models.user_directory_path),
        ),
    ]
