# Generated by Django 3.2.9 on 2021-11-26 20:43

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_date_joined_user_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to=users.models.user_directory_path),
        ),
    ]
