# Generated by Django 3.2.9 on 2022-03-07 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swings', '0004_alter_swing_recording'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swing',
            name='speed',
            field=models.FloatField(null=True),
        ),
    ]
